### ISSUE TITLE
Congrats: You just created monads in Python

### ISSUE THREAD

**Issue by 3noch** [yawaramin/lambdak#1]
I'm guessing you realize this, but your README does not mention Monad anywhere, even though that's essentially what you've done with lambdak. I like it. :D

**Comment by yawaramin** [comment]
Thanks! :-) I figured it was the continuation monad, but I didn't bother to research it. I generally don't care about extracting the monadic 'pattern' out of my types in languages where I don't have nice syntax sugar like `do` notation.

**Comment by 3noch** [comment]
Haha, I'm not sure which monad it is either. I'd have to look deeper at the implementation. After looking at your code I thought it would have been an incredible coincidence for you write your code with nested lambdas, just like traditional monadic code (without do notation). It's pretty interesting that Python's expression-only `lambda`s sort of recreate the exact same problem that Haskell found itself in before Wadler, et al, discovered Monad!
